"""ORCA input generation.

The generated input is a faithful rendering of a :class:`QMJobSpec` -- nothing is
added that the specification did not ask for, and nothing scientific is defaulted
silently.  In particular the simple-input line contains exactly the method, basis,
optional dispersion correction, optional implicit solvation, the requested run type,
and the requested convergence tiers.

Charge and multiplicity go on the coordinate block, where ORCA expects them, and are
taken from the structure rather than assumed.
"""

from __future__ import annotations

from pathlib import Path

from polymer_engine.qm.spec import JobKind, QMJobSpec

#: JobKind -> the ORCA run-type keywords it needs.
RUN_TYPE_KEYWORDS: dict[JobKind, tuple[str, ...]] = {
    JobKind.SINGLE_POINT: (),
    JobKind.OPTIMIZATION: ("Opt",),
    JobKind.FREQUENCY: ("Freq",),
    JobKind.OPT_FREQ: ("Opt", "Freq"),
    JobKind.TORSION_SCAN: ("Opt",),
    JobKind.CONFORMER: ("Opt",),
}


def build_input(spec: QMJobSpec) -> str:
    """Render an ORCA input file for ``spec``."""
    keywords: list[str] = [spec.method, spec.basis]
    if spec.dispersion:
        keywords.append(spec.dispersion)
    keywords.extend(RUN_TYPE_KEYWORDS[spec.kind])
    keywords.append(spec.scf_convergence)
    if spec.requires_geometry_convergence:
        keywords.append(spec.geom_convergence)
    if spec.solvation_model and spec.solvent:
        keywords.append(f"{spec.solvation_model}({spec.solvent})")
    keywords.extend(spec.extra_keywords)

    lines: list[str] = [
        f"# {spec.label} -- generated by polymer-engine",
        f"# job kind: {spec.kind.value}",
        f"# fingerprint: {spec.fingerprint()}",
    ]
    if spec.notes:
        for note in spec.notes.splitlines():
            lines.append(f"# {note}")
    lines.append("! " + " ".join(keywords))
    lines.append("")

    # %maxcore is per core, which is what ORCA means by it.
    lines.append(f"%maxcore {spec.memory_mb_per_core}")
    if spec.n_procs > 1:
        lines.append(f"%pal nprocs {spec.n_procs} end")
    lines.append("")

    lines.append("%scf")
    lines.append(f"  MaxIter {spec.max_scf_iterations}")
    lines.append("end")
    lines.append("")

    if spec.requires_geometry_convergence:
        lines.append("%geom")
        lines.append(f"  MaxIter {spec.max_geom_iterations}")
        if spec.kind is JobKind.TORSION_SCAN and spec.torsion is not None:
            torsion = spec.torsion
            a, b, c, d = torsion.atoms
            lines.append("  Scan")
            lines.append(
                f"    D {a} {b} {c} {d} = {torsion.start_deg:.4f}, "
                f"{torsion.stop_deg:.4f}, {torsion.n_points}"
            )
            lines.append("  end")
        lines.append("end")
        lines.append("")

    for block in spec.extra_blocks:
        lines.append(block.rstrip())
        lines.append("")

    lines.append(f"* xyz {spec.structure.charge} {spec.structure.multiplicity}")
    lines.extend(atom.as_line() for atom in spec.structure.atoms)
    lines.append("*")
    lines.append("")
    return "\n".join(lines)


def write_input(spec: QMJobSpec, directory: str | Path, *, filename: str | None = None) -> Path:
    """Write the ORCA input for ``spec`` into ``directory``."""
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / (filename or f"{spec.label}.inp")
    path.write_text(build_input(spec), encoding="utf-8")
    return path


__all__ = ["RUN_TYPE_KEYWORDS", "build_input", "write_input"]
