"""System validation: a malformed archive must never become a valid scientific system."""

from __future__ import annotations

import shutil
import tarfile
from pathlib import Path

import pytest

from polymer_engine.core.models import GateStatus
from polymer_engine.core.provenance import ProvenanceGraph
from polymer_engine.simulation.formats import read_gro, read_topology, read_xvg
from polymer_engine.simulation.system import (
    build_manifest,
    classify_artifact,
    import_archive,
    import_directory,
    validate_system,
)

VALID = Path(__file__).resolve().parents[1] / "fixtures" / "systems" / "valid_system"


@pytest.fixture
def system(tmp_path: Path) -> Path:
    target = tmp_path / "system"
    shutil.copytree(VALID, target)
    return target


def gate(report, name: str):
    return next(g for g in report.gates if g.gate == name)


# ==========================================================================
# Parsers
# ==========================================================================
class TestGroParsing:
    def test_valid_file(self) -> None:
        gro = read_gro(VALID / "system.gro")
        assert gro.n_atoms == 68
        assert gro.positions.shape == (68, 3)
        assert gro.box[:3] == (3.0, 3.0, 3.0)
        assert gro.positions_finite
        assert gro.residue_names[0] == "POL"
        assert gro.atom_names[0] == "C1"

    def test_truncated_file_is_rejected(self, tmp_path: Path) -> None:
        from polymer_engine.core.errors import SystemValidationError

        path = tmp_path / "short.gro"
        path.write_text("title\n100\n" + "".join(f"{1:5d}{'POL':<5s}{'C':>5s}{i:5d}{0.0:8.3f}{0.0:8.3f}{0.0:8.3f}\n" for i in range(3)))
        with pytest.raises(SystemValidationError, match="truncated"):
            read_gro(path)

    def test_non_integer_atom_count_is_rejected(self, tmp_path: Path) -> None:
        from polymer_engine.core.errors import SystemValidationError

        path = tmp_path / "bad.gro"
        path.write_text("title\nnot-a-number\n1 1 1\n")
        with pytest.raises(SystemValidationError, match="not an integer"):
            read_gro(path)

    def test_too_few_lines(self, tmp_path: Path) -> None:
        from polymer_engine.core.errors import SystemValidationError

        path = tmp_path / "tiny.gro"
        path.write_text("only one line\n")
        with pytest.raises(SystemValidationError):
            read_gro(path)


class TestTopologyParsing:
    def test_includes_and_molecule_types_resolve(self) -> None:
        topology = read_topology(VALID / "topol.top", include_dirs=[VALID])
        assert topology.molecule_types["POL"].n_atoms == 8
        assert topology.molecule_types["SOL"].n_atoms == 3
        assert topology.molecules == [("POL", 1), ("SOL", 20)]
        assert topology.total_atoms == 68
        assert topology.missing_includes == []

    def test_library_includes_are_not_missing_files(self, tmp_path: Path) -> None:
        path = tmp_path / "topol.top"
        path.write_text('#include <charmm36.ff/forcefield.itp>\n\n[ molecules ]\nSOL 1\n')
        topology = read_topology(path)
        assert "charmm36.ff/forcefield.itp" in topology.includes
        assert topology.missing_includes == [], "angle-bracket includes resolve at run time"

    def test_missing_local_include_is_recorded(self, tmp_path: Path) -> None:
        path = tmp_path / "topol.top"
        path.write_text('#include "absent.itp"\n\n[ molecules ]\nSOL 1\n')
        assert read_topology(path).missing_includes == ["absent.itp"]

    def test_circular_includes_terminate(self, tmp_path: Path) -> None:
        (tmp_path / "a.itp").write_text('#include "b.itp"\n')
        (tmp_path / "b.itp").write_text('#include "a.itp"\n')
        topology = read_topology(tmp_path / "a.itp")
        assert topology.missing_includes == []

    def test_ifdef_blocks_are_honoured(self, tmp_path: Path) -> None:
        path = tmp_path / "topol.top"
        path.write_text(
            "[ moleculetype ]\nA 3\n[ atoms ]\n1 x 1 A a 1 0 1\n"
            "#ifdef POSRES\n[ moleculetype ]\nB 3\n[ atoms ]\n1 x 1 B b 1 0 1\n#endif\n"
            "[ molecules ]\nA 1\n"
        )
        topology = read_topology(path)
        assert "A" in topology.molecule_types
        assert "B" not in topology.molecule_types, "an inactive #ifdef block must not define a type"


class TestXvgParsing:
    def test_metadata_and_data(self, tmp_path: Path) -> None:
        path = tmp_path / "density.xvg"
        path.write_text(
            '# generated by gmx energy\n'
            '@    title "Density"\n'
            '@    xaxis  label "Time (ps)"\n'
            '@    yaxis  label "kg/m\\S3\\N"\n'
            '@ s0 legend "Density"\n'
            "0.0  1000.0\n10.0 1010.0\n20.0  995.0\n"
        )
        data = read_xvg(path)
        assert data.n_points == 3
        assert data.title == "Density"
        assert data.legends == ["Density"]
        assert data.y.tolist() == [1000.0, 1010.0, 995.0]

    def test_ragged_rows_are_rejected(self, tmp_path: Path) -> None:
        from polymer_engine.core.errors import SystemValidationError

        path = tmp_path / "bad.xvg"
        path.write_text("0 1 2\n1 2\n")
        with pytest.raises(SystemValidationError, match="Ragged"):
            read_xvg(path)

    def test_empty_data_is_rejected(self, tmp_path: Path) -> None:
        from polymer_engine.core.errors import SystemValidationError

        path = tmp_path / "empty.xvg"
        path.write_text("# only comments\n@ title \"nothing\"\n")
        with pytest.raises(SystemValidationError, match="no numeric data"):
            read_xvg(path)


# ==========================================================================
# Artifact classification
# ==========================================================================
@pytest.mark.parametrize(
    "name,kind",
    [
        ("system.gro", "coordinates"),
        ("topol.top", "topology"),
        ("polymer.itp", "include_topology"),
        ("charmm36.prm", "forcefield"),
        ("npt.mdp", "mdp"),
        ("index.ndx", "index"),
        ("traj.xtc", "trajectory"),
        ("readme.txt", "other"),
    ],
)
def test_artifact_classification(name: str, kind: str) -> None:
    assert classify_artifact(Path(name)) == kind


# ==========================================================================
# Validation gates
# ==========================================================================
class TestValidation:
    def test_a_valid_system_passes_every_gate(self, system: Path) -> None:
        report = validate_system(system)
        assert report.status is GateStatus.PASS
        assert report.promotable is True

    def test_atom_counts_are_actually_checked(self, system: Path) -> None:
        assert gate(validate_system(system), "topology_matches_coordinates").value == 68

    def test_missing_topology_fails(self, system: Path) -> None:
        (system / "topol.top").unlink()
        report = validate_system(system)
        assert gate(report, "topology_present").status is GateStatus.FAIL
        assert report.promotable is False

    def test_missing_coordinates_fails(self, system: Path) -> None:
        (system / "system.gro").unlink()
        report = validate_system(system)
        assert gate(report, "coordinates_present").status is GateStatus.FAIL
        assert report.promotable is False

    def test_missing_include_fails(self, system: Path) -> None:
        (system / "water.itp").unlink()
        report = validate_system(system)
        assert gate(report, "topology_includes").status is GateStatus.FAIL
        assert report.promotable is False

    def test_atom_count_mismatch_fails(self, system: Path) -> None:
        """Change the topology so it no longer describes the coordinate file."""
        top = system / "topol.top"
        top.write_text(top.read_text().replace("SOL         20", "SOL         19"))
        report = validate_system(system)
        mismatch = gate(report, "topology_matches_coordinates")
        assert mismatch.status is GateStatus.FAIL
        assert mismatch.value == 68 and mismatch.threshold == 65

    def test_unresolvable_molecule_type_is_inconclusive_not_pass(self, system: Path) -> None:
        """Cannot verify is not the same as verified."""
        (system / "water.itp").write_text("; emptied\n")
        report = validate_system(system)
        assert gate(report, "topology_matches_coordinates").status is GateStatus.INCONCLUSIVE
        assert report.promotable is False, "inconclusive must block promotion"

    def test_non_finite_coordinates_fail(self, system: Path) -> None:
        gro = system / "system.gro"
        lines = gro.read_text().splitlines()
        lines[2] = lines[2][:20] + f"{'NaN':>8s}" + lines[2][28:]
        gro.write_text("\n".join(lines) + "\n")
        report = validate_system(system)
        assert gate(report, "coordinates_finite").status is GateStatus.FAIL

    def test_missing_box_fails_when_required(self, system: Path) -> None:
        gro = system / "system.gro"
        lines = gro.read_text().splitlines()
        gro.write_text("\n".join(lines[:-1]) + "\n")
        assert gate(validate_system(system), "box_defined").status is GateStatus.FAIL
        assert gate(validate_system(system, require_box=False), "box_defined").status is GateStatus.WARN

    def test_zero_box_dimension_fails(self, system: Path) -> None:
        gro = system / "system.gro"
        lines = gro.read_text().splitlines()
        lines[-1] = f"{0.0:10.5f}{3.0:10.5f}{3.0:10.5f}"
        gro.write_text("\n".join(lines) + "\n")
        assert gate(validate_system(system), "box_defined").status is GateStatus.FAIL

    def test_contents_larger_than_the_box_fail(self, system: Path) -> None:
        """A molecule wider than its periodic box interacts with its own image."""
        gro = system / "system.gro"
        lines = gro.read_text().splitlines()
        lines[-1] = f"{0.5:10.5f}{0.5:10.5f}{0.5:10.5f}"
        gro.write_text("\n".join(lines) + "\n")
        assert gate(validate_system(system), "contents_fit_box").status is GateStatus.FAIL

    def test_missing_molecules_section_fails(self, system: Path) -> None:
        top = system / "topol.top"
        text = top.read_text()
        top.write_text(text[: text.index("[ molecules ]")])
        assert gate(validate_system(system), "molecules_section").status is GateStatus.FAIL

    def test_empty_directory_fails(self, tmp_path: Path) -> None:
        empty = tmp_path / "nothing"
        empty.mkdir()
        report = validate_system(empty)
        assert report.promotable is False

    def test_nonexistent_directory_fails(self, tmp_path: Path) -> None:
        report = validate_system(tmp_path / "absent")
        assert report.status is GateStatus.FAIL


# ==========================================================================
# Manifest and import
# ==========================================================================
class TestManifest:
    def test_manifest_records_a_digest_per_file(self, system: Path) -> None:
        manifest = build_manifest(system)
        assert len(manifest.artifacts) == 4
        assert all(len(a.sha256) == 64 for a in manifest.artifacts)
        assert Path(manifest.coordinates).name == "system.gro"
        assert Path(manifest.topology).name == "topol.top"

    def test_manifest_round_trips(self, system: Path, tmp_path: Path) -> None:
        from polymer_engine.simulation.system import SystemManifest

        original = build_manifest(system)
        path = original.write(tmp_path / "m.json")
        restored = SystemManifest.load(path)
        assert restored.coordinates == original.coordinates
        assert len(restored.artifacts) == len(original.artifacts)

    def test_replica_gro_files_do_not_shadow_the_system_coordinates(self, system: Path) -> None:
        """A per-stage .gro in a subdirectory must not be picked as system input."""
        replica = system / "replica_01"
        replica.mkdir()
        (replica / "npt.gro").write_text((system / "system.gro").read_text())
        assert Path(build_manifest(system).coordinates).name == "system.gro"


class TestImport:
    def test_archive_import_end_to_end(self, tmp_path: Path) -> None:
        archive = tmp_path / "job.tgz"
        with tarfile.open(archive, "w:gz") as tf:
            tf.add(VALID, arcname="charmm-gui-1234")
        graph = ProvenanceGraph()
        imported = import_archive(archive, tmp_path / "out", graph=graph, source={"provider": "charmm_gui"})
        assert imported.usable is True
        assert imported.manifest.source["archive_sha256"]
        assert imported.artifact_id is not None
        # lineage: system -> archive
        assert graph.ancestors(imported.artifact_id)

    def test_archive_with_missing_topology_is_not_usable(self, tmp_path: Path) -> None:
        staging = tmp_path / "staging"
        shutil.copytree(VALID, staging)
        (staging / "topol.top").unlink()
        archive = tmp_path / "bad.tgz"
        with tarfile.open(archive, "w:gz") as tf:
            tf.add(staging, arcname="job")
        imported = import_archive(archive, tmp_path / "out")
        assert imported.usable is False

    def test_directory_import(self, system: Path) -> None:
        imported = import_directory(system)
        assert imported.usable is True
        assert imported.extraction is None
